<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClassesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('classes')->upsert([
            [
                'id' => 1,
                'code_diplome' => 'EB101',
                'libelle_long' => 'GE_EB_S_1A-Electricité de Bâtiment (1A)-2025',
                'filiere_id' => 1,
                'niveau_id' => 1,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 2,
                'code_diplome' => 'MA101',
                'libelle_long' => 'BTP_MA_S_1A-Menuiserie Aluminium (1A)-2025',
                'filiere_id' => 2,
                'niveau_id' => 1,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 3,
                'code_diplome' => 'MA102',
                'libelle_long' => 'BTP_MA_S_1A-Menuiserie Aluminium (1A)-2025',
                'filiere_id' => 2,
                'niveau_id' => 1,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 4,
                'code_diplome' => 'EB102',
                'libelle_long' => 'GE_EB_S_1A-Electricité de Bâtiment (1A)-2025',
                'filiere_id' => 1,
                'niveau_id' => 1,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 5,
                'code_diplome' => 'OSCC102',
                'libelle_long' => 'TH_OSCC_S_1A-Ouvrier Spécialisé en Coupe et Couture (1A)-2025',
                'filiere_id' => 3,
                'niveau_id' => 1,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 6,
                'code_diplome' => 'OSCC101',
                'libelle_long' => 'TH_OSCC_S_1A-Ouvrier Spécialisé en Coupe et Couture (1A)-2025',
                'filiere_id' => 3,
                'niveau_id' => 1,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 7,
                'code_diplome' => 'EB103',
                'libelle_long' => 'GE_EB_S_1A-Electricité de Bâtiment (1A)-2025',
                'filiere_id' => 1,
                'niveau_id' => 1,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 8,
                'code_diplome' => 'EIT101',
                'libelle_long' => "GE_EIT_Q_1A-Électricité d'Installation (1A)-2025",
                'filiere_id' => 4,
                'niveau_id' => 2,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 9,
                'code_diplome' => 'AEFGT101',
                'libelle_long' => "FGT_AEFGT_Q_1A-Agent d'Entretien en Froid et Génie Thermique (1A)-2025",
                'filiere_id' => 5,
                'niveau_id' => 2,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 10,
                'code_diplome' => 'AEFGT102',
                'libelle_long' => "FGT_AEFGT_Q_1A-Agent d'Entretien en Froid et Génie Thermique (1A)-2025",
                'filiere_id' => 5,
                'niveau_id' => 2,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 11,
                'code_diplome' => 'EIT102',
                'libelle_long' => "GE_EIT_Q_1A-Électricité d'Installation (1A)-2025",
                'filiere_id' => 4,
                'niveau_id' => 2,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 12,
                'code_diplome' => 'TDB101',
                'libelle_long' => 'BTP_TDB_T_1A-Technicien Dessinateur de Bâtiment (1A)-2025',
                'filiere_id' => 6,
                'niveau_id' => 3,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 13,
                'code_diplome' => 'AA101',
                'libelle_long' => 'GC_AA_T_1A-Assistant Administratif (1A)-2025',
                'filiere_id' => 7,
                'niveau_id' => 3,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 14,
                'code_diplome' => 'AA102',
                'libelle_long' => 'GC_AA_T_1A-Assistant Administratif (1A)-2025',
                'filiere_id' => 7,
                'niveau_id' => 3,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 15,
                'code_diplome' => 'TDB102',
                'libelle_long' => 'BTP_TDB_T_1A-Technicien Dessinateur de Bâtiment (1A)-2025',
                'filiere_id' => 6,
                'niveau_id' => 3,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 16,
                'code_diplome' => 'TFCC101',
                'libelle_long' => 'FGT_TFCC_T_1A-Technicien en Froid Commercial et Climatisation (1A)-2025',
                'filiere_id' => 8,
                'niveau_id' => 3,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 17,
                'code_diplome' => 'EB104',
                'libelle_long' => 'GE_EB_S_1A-Electricité de Bâtiment (1A)-2025',
                'filiere_id' => 1,
                'niveau_id' => 1,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 18,
                'code_diplome' => 'MA103',
                'libelle_long' => 'BTP_MA_S_1A-Menuiserie Aluminium (1A)-2025',
                'filiere_id' => 2,
                'niveau_id' => 1,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 19,
                'code_diplome' => 'DEV101',
                'libelle_long' => 'DIA_DEV_TS_1A-Développement Digital (1A)-2025',
                'filiere_id' => 9,
                'niveau_id' => 4,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 20,
                'code_diplome' => 'GE101',
                'libelle_long' => 'GC_GE_TS_1A-Gestion des Entreprises (1A)-2025',
                'filiere_id' => 10,
                'niveau_id' => 4,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 21,
                'code_diplome' => 'GE103',
                'libelle_long' => 'GC_GE_TS_1A-Gestion des Entreprises (1A)-2025',
                'filiere_id' => 10,
                'niveau_id' => 4,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 22,
                'code_diplome' => 'GC101',
                'libelle_long' => 'BTP_GC_TS_1A-Technicien Spécialisé Génie Civil (1A)-2025',
                'filiere_id' => 11,
                'niveau_id' => 4,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 23,
                'code_diplome' => 'GE102',
                'libelle_long' => 'GC_GE_TS_1A-Gestion des Entreprises (1A)-2025',
                'filiere_id' => 10,
                'niveau_id' => 4,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 24,
                'code_diplome' => 'DEV102',
                'libelle_long' => 'DIA_DEV_TS_1A-Développement Digital (1A)-2025',
                'filiere_id' => 9,
                'niveau_id' => 4,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 25,
                'code_diplome' => 'GC102',
                'libelle_long' => 'BTP_GC_TS_1A-Technicien Spécialisé Génie Civil (1A)-2025',
                'filiere_id' => 11,
                'niveau_id' => 4,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 26,
                'code_diplome' => 'GE104',
                'libelle_long' => 'GC_GE_TS_1A-Gestion des Entreprises (1A)-2025',
                'filiere_id' => 10,
                'niveau_id' => 4,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 27,
                'code_diplome' => 'GEOCM301',
                'libelle_long' => 'GC_GEOCM_TS_3A-Gestion des Entreprises option Commerce et Marketing (3A)-2025',
                'filiere_id' => 12,
                'niveau_id' => 4,
                'annee' => 3,
                'saison' => 3,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 28,
                'code_diplome' => 'DEVOWFS201',
                'libelle_long' => 'DIA_DEVOWFS_TS_2A-Développement Digital option Web Full Stack (2A)-2025',
                'filiere_id' => 13,
                'niveau_id' => 4,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 29,
                'code_diplome' => 'GEOCM302',
                'libelle_long' => 'GC_GEOCM_TS_3A-Gestion des Entreprises option Commerce et Marketing (3A)-2025',
                'filiere_id' => 12,
                'niveau_id' => 4,
                'annee' => 3,
                'saison' => 3,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 30,
                'code_diplome' => 'TDB201',
                'libelle_long' => 'BTP_TDB_T_2A-Technicien Dessinateur de Bâtiment (2A)-2025',
                'filiere_id' => 6,
                'niveau_id' => 3,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 31,
                'code_diplome' => 'GEOCF201',
                'libelle_long' => 'GC_GEOCF_TS_2A-Gestion des Entreprises option Comptabilité et Finance (2A)-2025',
                'filiere_id' => 14,
                'niveau_id' => 4,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 32,
                'code_diplome' => 'GEOCM201',
                'libelle_long' => 'GC_GEOCM_TS_2A-Gestion des Entreprises option Commerce et Marketing (2A)-2025',
                'filiere_id' => 12,
                'niveau_id' => 4,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 33,
                'code_diplome' => 'GEOCF301',
                'libelle_long' => 'GC_GEOCF_TS_3A-Gestion des Entreprises option Comptabilité et Finance (3A)-2025',
                'filiere_id' => 14,
                'niveau_id' => 4,
                'annee' => 3,
                'saison' => 3,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 34,
                'code_diplome' => 'AAOCP301',
                'libelle_long' => 'GC_AAOCP_T_3A-Assistant Administratif option Comptabilité (3A)-2025',
                'filiere_id' => 15,
                'niveau_id' => 3,
                'annee' => 3,
                'saison' => 3,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 35,
                'code_diplome' => 'AEFGTOF201',
                'libelle_long' => 'FGT_AEFGTOF_Q_2A-Agent d`Entretien en Froid et Génie Thermique option Frigoriste (2A)-2025',
                'filiere_id' => 16,
                'niveau_id' => 2,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 36,
                'code_diplome' => 'EIT202',
                'libelle_long' => 'GE_EIT_Q_2A-Électricité d`Installation (2A)-2025',
                'filiere_id' => 4,
                'niveau_id' => 2,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 37,
                'code_diplome' => 'EIT201',
                'libelle_long' => 'GE_EIT_Q_2A-Électricité d`Installation (2A)-2025',
                'filiere_id' => 4,
                'niveau_id' => 2,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 38,
                'code_diplome' => 'GC201',
                'libelle_long' => 'BTP_GC_TS_2A-Technicien Spécialisé Génie Civil (2A)-2025',
                'filiere_id' => 11,
                'niveau_id' => 4,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 39,
                'code_diplome' => 'TDB202',
                'libelle_long' => 'BTP_TDB_T_2A-Technicien Dessinateur de Bâtiment (2A)-2025',
                'filiere_id' => 6,
                'niveau_id' => 3,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 40,
                'code_diplome' => 'GEOCM202',
                'libelle_long' => 'GC_GEOCM_TS_2A-Gestion des Entreprises option Commerce et Marketing (2A)-2025',
                'filiere_id' => 12,
                'niveau_id' => 4,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 41,
                'code_diplome' => 'GEOCF202',
                'libelle_long' => 'GC_GEOCF_TS_2A-Gestion des Entreprises option Comptabilité et Finance (2A)-2025',
                'filiere_id' => 14,
                'niveau_id' => 4,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 42,
                'code_diplome' => 'GEOCF302',
                'libelle_long' => 'GC_GEOCF_TS_3A-Gestion des Entreprises option Comptabilité et Finance (3A)-2025',
                'filiere_id' => 14,
                'niveau_id' => 4,
                'annee' => 3,
                'saison' => 3,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 43,
                'code_diplome' => 'AAOCP201',
                'libelle_long' => 'GC_AAOCP_T_2A-Assistant Administratif option Comptabilité (2A)-2025',
                'filiere_id' => 15,
                'niveau_id' => 3,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 44,
                'code_diplome' => 'AAOC201',
                'libelle_long' => 'GC_AAOC_T_2A-Assistant Administratif option Commerce (2A)-2025',
                'filiere_id' => 17,
                'niveau_id' => 3,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 45,
                'code_diplome' => 'TSGE201',
                'libelle_long' => 'AGC_TSGE_TS_RCDS_2A-(CDS)Technicien Spécialisé en Gestion des Entreprises (2A)-2025',
                'filiere_id' => 18,
                'niveau_id' => 4,
                'annee' => 2,
                'saison' => 2,
                'is_cds' => 1,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 46,
                'code_diplome' => 'TSGE301',
                'libelle_long' => 'AGC_TSGE_TS_RCDS_3A-(CDS)Technicien Spécialisé en Gestion des Entreprises (3A)-2025',
                'filiere_id' => 18,
                'niveau_id' => 4,
                'annee' => 3,
                'saison' => 3,
                'is_cds' => 1,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 47,
                'code_diplome' => 'PIE101',
                'libelle_long' => 'GC_PIE_FQ_1A-Programme d`Innovation Entrepreneuriale (1A)-2025',
                'filiere_id' => 19,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 48,
                'code_diplome' => 'PIE102',
                'libelle_long' => 'GC_PIE_FQ_1A-Programme d`Innovation Entrepreneuriale (1A)-2025',
                'filiere_id' => 19,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 49,
                'code_diplome' => 'PIE103',
                'libelle_long' => 'GC_PIE_FQ_1A-Programme d`Innovation Entrepreneuriale (1A)-2025',
                'filiere_id' => 19,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 50,
                'code_diplome' => 'ACF101',
                'libelle_long' => 'GC_ACF_FQ_RCDS_1A-(CDS)Audit Comptable et Financier (1A)-2025',
                'filiere_id' => 20,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 1,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 51,
                'code_diplome' => 'GEOCF101',
                'libelle_long' => 'GC_GEOCF_TS_RCDS_1A-(CDS)Gestion des Entreprises option Comptabilité et Finance (1A)-2025',
                'filiere_id' => 14,
                'niveau_id' => 4,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 1,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 52,
                'code_diplome' => 'PIE104',
                'libelle_long' => 'GC_PIE_FQ_1A-Programme d`Innovation Entrepreneuriale (1A)-2025',
                'filiere_id' => 19,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 53,
                'code_diplome' => 'PIE105',
                'libelle_long' => 'GC_PIE_FQ_1A-Programme d`Innovation Entrepreneuriale (1A)-2025',
                'filiere_id' => 19,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 54,
                'code_diplome' => 'SME101',
                'libelle_long' => 'DIA_SME_FQ_1A-Spécialiste en Microsoft Excel (1A)-2025',
                'filiere_id' => 21,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 55,
                'code_diplome' => 'SMW101',
                'libelle_long' => 'DIA_SMW_FQ_1A-Spécialiste en Microsoft Word (1A)-2025',
                'filiere_id' => 22,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 56,
                'code_diplome' => 'SME104',
                'libelle_long' => 'DIA_SME_FQ_1A-Spécialiste en Microsoft Excel (1A)-2025',
                'filiere_id' => 21,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 57,
                'code_diplome' => 'SMW104',
                'libelle_long' => 'DIA_SMW_FQ_1A-Spécialiste en Microsoft Word (1A)-2025',
                'filiere_id' => 22,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 58,
                'code_diplome' => 'SME102',
                'libelle_long' => 'DIA_SME_FQ_1A-Spécialiste en Microsoft Excel (1A)-2025',
                'filiere_id' => 21,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 59,
                'code_diplome' => 'SMW102',
                'libelle_long' => 'DIA_SMW_FQ_1A-Spécialiste en Microsoft Word (1A)-2025',
                'filiere_id' => 22,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 60,
                'code_diplome' => 'SME103',
                'libelle_long' => 'DIA_SME_FQ_1A-Spécialiste en Microsoft Excel (1A)-2025',
                'filiere_id' => 21,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 61,
                'code_diplome' => 'SMW103',
                'libelle_long' => 'DIA_SMW_FQ_1A-Spécialiste en Microsoft Word (1A)-2025',
                'filiere_id' => 22,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 62,
                'code_diplome' => 'SME105',
                'libelle_long' => 'DIA_SME_FQ_1A-Spécialiste en Microsoft Excel (1A)-2025',
                'filiere_id' => 21,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 63,
                'code_diplome' => 'SMW105',
                'libelle_long' => 'DIA_SMW_FQ_1A-Spécialiste en Microsoft Word (1A)-2025',
                'filiere_id' => 22,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 64,
                'code_diplome' => 'SME106',
                'libelle_long' => 'DIA_SME_FQ_1A-Spécialiste en Microsoft Excel (1A)-2025',
                'filiere_id' => 21,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
            [
                'id' => 65,
                'code_diplome' => 'SMW106',
                'libelle_long' => 'DIA_SMW_FQ_1A-Spécialiste en Microsoft Word (1A)-2025',
                'filiere_id' => 22,
                'niveau_id' => 5,
                'annee' => 1,
                'saison' => 1,
                'is_cds' => 0,
                'created_at' => '2026-09-19 06:46:05',
                'updated_at' => '2026-09-19 06:46:05',
            ],
        ], ['id'], [
            'code_diplome', 'libelle_long', 'filiere_id', 'niveau_id',
            'annee', 'saison', 'is_cds', 'created_at', 'updated_at',
        ]);
    }
}